
ERROR_NETWORK_CONNECTION_FAILURE = 1
ERROR_NETWORK_TIMEOUT            = 2
ERROR_NETWORK_AUTHENTICATION     = 3
ERROR_NETWORK_CANCELLED          = 4
ERROR_NETWORK_UNKNOWN            = 5
ERROR_UNKNOWN                    = 99

ERROR_SERVER_OK                  = 200
ERROR_SERVER_ERROR               = 500
ERROR_SERVER_NOT_IMPLEMENTED     = 501
ERROR_SERVER_BAD_GATEWAY         = 502
ERROR_SERVER_SERVICE_UNAVAILABLE = 503
ERROR_SERVER_GATEWAY_TIMEOUT     = 504
ERROR_SERVER_FORBIDDEN           = 403

ERROR_INVALID_RESULT             = 1001
ERROR_INVALID_PARAMETERS         = 1002
ERROR_SERVER_INVALID_ACTION      = 1003
ERROR_REDIS_FAILED               = 1004
ERROR_INVALID_SESSION_ID         = 1005
