
local Event = {}

Event.ENTER_SCENE                 = ENTER_SCENE_EVENT
Event.EXIT_SCENE                  = EXIT_SCENE_EVENT
Event.ENTER_TRANSITION_DID_FINISH = ENTER_TRANSITION_DID_FINISH_EVENT
Event.EXIT_TRANSITION_DID_START   = EXIT_TRANSITION_DID_START_EVENT
Event.CLEANUP                     = CLEANUP_EVENT
Event.ENTER_FRAME                 = ENTER_FRAME_EVENT

return Event
