
local Event = {}

Event.ENTER_SCENE                 = "ENTER_SCENE"
Event.EXIT_SCENE                  = "EXIT_SCENE"
Event.ENTER_TRANSITION_DID_FINISH = "ENTER_TRANSITION_DID_FINISH"
Event.EXIT_TRANSITION_DID_START   = "EXIT_TRANSITION_DID_START"
Event.CLEANUP                     = "CLEANUP"

Event.ENTER_FRAME                 = "ENTER_FRAME"

Event.TOUCH_BEGAN                 = "TOUCH_BEGAN"
Event.TOUCH_MOVED                 = "TOUCH_MOVED"
Event.TOUCH_ENDED                 = "TOUCH_ENDED"
Event.TOUCH_CANCELLED             = "TOUCH_CANCELLED"
Event.TOUCH_CAPTURE_BEGAN         = "TOUCH_CAPTURE_BEGAN"
Event.TOUCH_CAPTURE_MOVED         = "TOUCH_CAPTURE_MOVED"
Event.TOUCH_CAPTURE_ENDED         = "TOUCH_CAPTURE_ENDED"
Event.TOUCH_CAPTURE_CANCELLED     = "TOUCH_CAPTURE_CANCELLED"

Event.MENU_ITEM_CLICKED           = "MENU_ITEM_CLICKED"

Event.ACCELERATE                  = "ACCELERATE"
Event.KEYPAD                      = "KEYPAD"

return Event
